### ISSUE TITLE
Review possible system font stack for the project

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/low-carbon-template#6]
Compare that of Wagtail vs. Tailwind latest

**Comment by thibaudcolas** [comment]
Here’s a diff between Wagtail’s system font stack and that of Tailwind. Tailwind in green, Wagtail in red:

```diff
+ui-sans-serif
--apple-system,
-BlinkMacSystemFont,
-"Segoe UI",
system-ui,
-Roboto,
-"Helvetica Neue",
-Arial,
sans-serif,
Apple Color Emoji,
"Segoe UI Emoji",
"Segoe UI Symbol",
"Noto Color Emoji",
```

So they both use the same emoji stacks. Tailwind uses `ui-sans-serif`, which is only supported on Apple from 2020 onwards. The Wagtail font stack uses more explicit fallbacks.

For our template, I like the idea of combining them both:

```css
font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, Roboto, "Helvetica Neue", Arial, sans-serif, Apple Color Emoji, "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
```

That way we get good support for older devices. What do you think @nandini584?

**Comment by nandini584** [comment]
I agree that this will improve the user experience as well. Shall I proceed to configure it in ```tailwind.config.js```?

**Comment by thibaudcolas** [comment]
Discussed with @nandini584, making the change in #10
